all:
	@echo " -= Interface com o Usuario =-"
	@nasm -f bin -o ../../../Temp/InterfaceVGA VGAExtensao.asm
	@nasm -f bin -o ../../../Temp/InterfaceCGA CGAExtensao.asm
	@nasm -f bin -o ../../../Temp/InterfaceMDA MDAExtensao.asm